### ISSUE TITLE
Pop-up should be dismissable (per URL / per domain)

### ISSUE THREAD

**Issue by nileshtrivedi** [nileshtrivedi/better#2]
Once dismissed, popup should not be shown on the same url/domain. Use cookies or localStorage for this.

**Comment by oxalorg** [comment]
To implement this, this is the approach I am thinking:

1. User goes to `evilUrl`
2. We test it with `urlPattern` until a match is found
3. User gets Better Popup
3. User clicks on dismiss
4. We store this data structure in localstorage using `chrome.storage.sync` api:

## Approach 1

```
{
	"dismissed": {
		"evilUrl": True,
	}
}
```

This way we can decide to stop processing after Step 1 itself.

One issue here could be multiple/wildcard regex won't be satisfied. Example if `urlPattern` is `https://evilUrl.(com|in)`.

## Approach 2

A better approach would be to store the `urlPattern` instead of `evilUrl`. This would mean we have to Perform `Step 2` and only then can we detect if the pattern has been dismissed.

```
{
	"dismissed": {
		"urlPattern": True,
	}
}
```

## Approach 3

A more expensive albeit space-saving approach can be to simply:

```
{
	"dismissed": ["urlPattern1", ...]
}
```

I'm leaning towards Approach #2, @nileshtrivedi any thoughts?

**Comment by oxalorg** [comment]
There's a problem with Stale entries/more manual way to enable/disable suggestions for a given URL. I think that can be implemented later on via Extension Popups like uBlock.

**Comment by oxalorg** [comment]
Apparently chrome.storage operations are async and immutable. So if we're storing data inside a `dismissed` dict then we need to first `get` it, update it, and then `set` it again.

An alternative could be to use keys like this: `dismiss@${urlPattern}` directly

**Comment by nileshtrivedi** [comment]
Why not just use `window.localStorage` in the contentscript? First check if the dismiss flag has been set to `true`. If not, then proceed to the `getMatch` message to background script. This will count towards the space usage of that domain, rather than for our extension.

Dismiss flag can be kept either for the entire pattern, or for the current URL. So, the stored value can be `{dismissPattern: true}` or `{dismissURLs: []}`. If I had to pick only one choice for this feature, I'd go with `urlPattern` as the dismiss flag. So the stored value can be `{dismissPattern: true}`.

**Comment by nileshtrivedi** [comment]
Ok, I just noticed that your PR uses contentscript only. This should work. :+1:

**Comment by oxalorg** [comment]
> Why not just use window.localStorage in the contentscript

But what if that domain is clearing the localStorage based on its own logic? 

Storing the details inside domain-specific localStorage won't allow us to populate "all dismissed domains" in the Options UI.

**Comment by oxalorg** [comment]
> Ok, I just noticed that your PR uses contentscript only. This should work. 👍

It still uses `chrome.storage.local` in `contentscript` which apparently stores the data inside extenstions storage (and not the domains storage).

**Comment by nileshtrivedi** [comment]
Ok, I think this is sensible. Let's go with what you have built. :+1:
